name: fun-with-jenkins-infra
description: A TypeScript program to deploy a virtual machine on Amazon EC2
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: vm-aws-typescript
